app_name: LivestormBar 
app_filename: LivestormBar.zip # Should match exactly the .zip file found in ./release/
s3_bucket_name: livestormbar # Must be unique

# More variables need to be added to your environment. See the readme
